# Generated by Django 2.2.28 on 2023-02-23 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weather',
            name='json_response',
        ),
        migrations.AddField(
            model_name='weather',
            name='currentTemp',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='weather',
            name='maxTemp',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='weather',
            name='minTemp',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='address_text',
            field=models.CharField(max_length=255),
        ),
    ]
